🔥 Blog app - controllers specs
roniy68/rails-blog pull request #6
Opened 2023-05-12 22:21 UTC by roniy68

# Highlights 🥇 

## What I Have Done: 
✅ Add RSpec as a gem to your project.
✅ Create a Request spec file for all your controllers.
✅ Make sure that for each action you check:
        * If response status was correct.
        * If a correct template was rendered.
        * If the response body includes correct placeholder text.

## Missed anything?
- [ ] Explained the purpose of this PR.
- [ ] Self reviewed the PR.
- [ ] Added or updated test cases.
- [ ] Informed of breaking changes, testing and migrations (if applicable).
- [ ] Updated documentation (if applicable).
- [ ] Attached screenshots (if applicable).

## Followed Rules: 
- Made sure [no linter errors](https://github.com/microverseinc/linters-config)
-  Followed [Github Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
-  Documented [professionaly](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- Follow our list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

![image](https://user-images.githubusercontent.com/77187003/236616649-e3722c25-e551-4a92-8bcb-00faaf2ff57c.png)

2023-05-12 22:59 UTC, Whoistolu requested changes
Hi @roniy68 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 22:59 UTC, Whoistolu commented on db/migrate/20230501154005_create_likes.rb
> +end
- [ ] [REQUIRED] Hello @roniy68 , great job so far with the tests 👍🏽 🥇  , however, there seem to be double migrations. Let's delete the other migrations that are not necessary. I had to delete almost 8 migrations files that are double before I was able to run the test. 
Let's fix this 💪🏽  

For example :
<img width="538" alt="Screenshot 2023-05-12 at 23 44 27" src="https://github.com/roniy68/rails-blog/assets/58692590/a1eef847-87e5-481d-8122-017119532f84">

<img width="1440" alt="Screenshot 2023-05-12 at 23 42 23" src="https://github.com/roniy68/rails-blog/assets/58692590/f9ec4cc6-8661-4e8a-94b6-2c90b9be42bf">

2023-05-13 01:05 UTC, roniy68 commented on db/migrate/20230501154005_create_likes.rb
> +end
😄 Fixed Migration. Now Should do fine

2023-05-13 01:18 UTC, Reem-lab approved these changes
Hi @roniy68, 🤩🔥 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/l41YmQjOz9qg2Ecow/giphy.gif"/>

## Highlights
- [ ] Great job on the functionaliy for the tests 💯
- [ ] Professional README 🔥
- [ ] Followed Gitflow 🔥

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 08:11 UTC, merged